services:
  - type: web
    name: bilibili-downloader
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --timeout 300 --workers 1 app:app"
    plan: free
