services:
  - type: web
    name: video-downloader
    env: python
    buildCommand: "apt-get update && apt-get install -y ffmpeg aria2 && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
